on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run Python Script
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Say 'Hello' with Chainguard
        uses: ./hello-world-docker-action # Uses an action in the root directory
        id: hello
